---
format: 
  pdf:
    include-in-header:
      text: |
        % tables
        \usepackage[l3]{csvsimple}
        \usepackage{nicematrix}
        \usepackage{multirow} % merge rows / columns
        \usepackage{booktabs}
        
        % right aligned columns in nicematrix
        \newcolumntype{Y}{>{\raggedleft\arraybackslash}X}
        
        % Captions and labels (Makes our Caption labels Grey and uppercase :D)
        \usepackage[singlelinecheck=off, font=small]{caption}
        \DeclareCaptionLabelFormat{AnimEco}{\textbf{\color{darkgray!75}\MakeUppercase{#1 #2}}}
        \captionsetup{labelformat=AnimEco,labelsep=quad}
        
        % equation labels
        \usepackage{mathtools,amssymb,amsthm}
        \newtagform{Eq}{(Eq. }{)}
        \usetagform{Eq}
editor: visual
csl: apa.csl
bibliography: Quant_Com_Group.bib
---

# Analysing:

# 1) Biodiversity of ant communities along an elevational gradient and

# 2) Taxonomic composition of arthropods along plant diversity gradient in the Jena Experiment

**Course:** Quantitative Community Ecology in R

**Authors:** Evangelos Karapoulis, Julian Nico Thiem, Gian Luca Naccarato

**Supervisors:** Felix May & Oksana Buzhdygan - Theoretical Ecology Lab

## Task 2)

### Step by step

1\) Does data responds linearly? –\> DCA to access gradient length

-   in our case SD = 1.5048 = Linear methods are the most powerful way

In this case, we still have to choose between:

1\. Constrained ordination method:

-   Redundancy Analysis (RDA)

2\. Unconstrained ordination methods:

-   Principle Component Analysis (PCA) +post hoc testing of predictor effects using envit() function

#### According to: Chapter 6 from: Borcard, D., Gillet, F. and Legendre, P. 2011. Numerical Ecology with R. Springer.

**Short thought on possible usage of Transformation (Hellinger-Standardization):**

-   Hellinger-Standardization can be used in linear ordination methods as they use the Euclidean Distance, which is sensitive to the double-zero problem (two species are both absent in several sites, which can artificially inflate the similarity between sites --\> absence of a species in different samples is wrongly interpreted as similarity)

-   in our dataset no zeros occur --\> Hellinger transformation is not needed fro this reason B**UT**

-   Hellinger transformation converts species abundances from absolute to relative values and then square roots them. This could be useful if we are not interested in changes of absolute species abundances, but relative abundances. E.g. if species A has abundance 30 in sample 1 and 20 in sample 2, and species B has abundance 3 in sample 1 and 2 in sample 2, the absolute change is 10 for species A and 1 for species B, but relative change is the same for both. If this is the purpose of this transformation, then Hellinger transformed data could be used also in other ordination methods, e.g. CA or CCA;

--\> so according to <https://www.davidzeleny.net/anadat-r/doku.php/en:confusions> we should not use the hellinger transformation because we already have a linear response??

**Decision between constrained and unconstrained methods:**

-   Constrained ordinations use an a prior hypothesis to produce the ordination plot (i.e. they relate a matrix of response variables to explanatory variables). They only display the variation in the data of the explanatory variables (versus unconstrained which display all the variation in the data).

-   An unconstrained ordination is useful for viewing overall patterns in the data, but constrained ordinations allow you to test hypotheses and discover trends that were hidden in the unconstrained ordination (i.e. masked by high variability and high correlation structure).

--\> still not sure which ones is the better choice (they are both very similar)

--\> but from the way she formulated the task, I would suggest to calculate a PCA first and than proceed with post-hoc vector fitting as she states it. However, I have also read in some articles that you can combine these to methods as well..

**Transformation of environmental data:**

-   we have presence absence data (functional plant groups)

-   and we have species diversity data (2,4,8,16) of sawn species, do weed need to transform them into categories (1,2,3,4,5)?

## Further Notes:

Here is a paper from the Jena Experiment dealing with anthropodes and plant diversity:

<https://doi.org/10.1016/j.baae.2017.09.014>
